# Checkpoints

<p>Imports</p>

In [2]:
from itertools import combinations, cycle
import glob
import re
from bs4 import BeautifulSoup
import numpy as np

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [17]:
#your code here
letters = ['A','B','C']
for combination in  combinations(letters, 2):
    print(combination)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [7]:
#your code here
rng = 10
for word in cycle(['Python', 'is', 'fun']):
    if rng <= 0:
        break
    print(word)
    rng -= 1
    


Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [12]:
#your code here

glob.glob('*.py')

['test.py']

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [1]:
html = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

In [3]:
#your code here
def extractP(html):
    soup = BeautifulSoup(html, 'html.parser')
    return soup.p.get_text()

extractP(html)

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [5]:
#your code here
text = 'AI is a transformative field of study that leverages advanced algorithms and computational models to enable machines to mimic human intelligence and perform tasks that traditionally required human cognition. With its ability to analyze vast amounts of data, AI has revolutionized industries such as healthcare, finance, and transportation, powering innovations like autonomous vehicles, personalized medicine, and intelligent virtual assistants. From machine learning and natural language processing to computer vision and neural networks, AI encompasses a wide range of techniques that enable systems to learn, reason, and make decisions autonomously, paving the way for a future where AI plays a pivotal role in enhancing efficiency, solving complex problems, and driving unprecedented progress across numerous domains.'
original_word = 'AI'
new_word = 'Artificial Intelligence'
def replaceWord(original_word,new_word,  text):
    return re.sub(original_word, new_word, text)

replaceWord(original_word=original_word, new_word=new_word, text=text)

'Artificial Intelligence is a transformative field of study that leverages advanced algorithms and computational models to enable machines to mimic human intelligence and perform tasks that traditionally required human cognition. With its ability to analyze vast amounts of data, Artificial Intelligence has revolutionized industries such as healthcare, finance, and transportation, powering innovations like autonomous vehicles, personalized medicine, and intelligent virtual assistants. From machine learning and natural language processing to computer vision and neural networks, Artificial Intelligence encompasses a wide range of techniques that enable systems to learn, reason, and make decisions autonomously, paving the way for a future where Artificial Intelligence plays a pivotal role in enhancing efficiency, solving complex problems, and driving unprecedented progress across numerous domains.'

**CP6**: Create a numpy array of 10 zeros.

In [8]:
#your code here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**CP7** Create a numpy array of the integers from 10 to 49.

In [9]:
#your code here
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [10]:
#your code here
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

<p>machine learning models need large amounts of data in order to increase thier accuracy by giving large amounts of different examples we can reduce overfitting</p>

<p> Large amount of data means lots of diverse amount of examples </p>

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

deep fake:  
creation of videos or images, that convincingly depict individuals saying or doing things they never actually did

one way of prevention could be impmenting a way to ensure that this technology is not used for malicious purpose and also building highly reliable method to detect deepfakes.

autonomous hacking: 

Training AI algorithms to autonomously discover and exploit vulnerabilities in computer systems, networks, or IoT devices, leading to widespread cyberattacks.

to defend against this or prevent one could also use AI to throughly test the system for vulnerability and improving the securty of the sytstem based on those vulnerabilities.